### ISSUE TITLE
1.18.2 Aternos server is crashing because of wrong ID numbers of SWDM blocks

### ISSUE THREAD

**Issue by kizuuuuuu** [AlaharranHonor/SWDecoM#7]
I was making my aternos server on 1.18.2, well its kind of broken version, maybe its so buggy on Aternos, but i added some mods and i got "Old" version at my server list, it was showing me that server is still starting even if its online. So i decided to remove all mods and adding them one by one and after I add one mod im starting server and checking if its working. Everything was fine until SWDM.

Log: https://mclo.gs/caF1SiP
A lot of block (or all of them) have different ID number

**Comment by Quarris** [comment]
Those errors happen when you introduce new blocks/items into an existing world. It's not an error and is not what is causing your server to crash
